### ISSUE TITLE
Registered Users can view listings

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v26-bears-team-06#18]
# User Story

As a `registered user` or an `unregistered user`
I want to view listings
So I can find listings I'm interested in

# Tasks

- [ ] Add a `listing` display page to allow all listings to be displayed & selected for update
- [ ] Create a BE API route in the BE to retrieve all `listing' data
- [ ] Allow registered users to view & maintain only their listings
