### ISSUE TITLE
Create a Home page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v26-bears-team-06#26]
# User Story

As a `registered user` or an `unregistered user`
I want to see all categories goods are filed under or search for goods I'm interested in
So I can effectively manage listings I create to sell & request services

# Tasks

- [ ] List of out all the categories available on the app
- [ ] Search for listings using information TBD

Create API routes in the BE
    - [ ]  Search for `categories` route
    - [ ]  Search for `listings` route (search criteria TBD)
