### ISSUE TITLE
Authenticate Users

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v26-bears-team-06#3]
Incorporate user registration & authentication to ensure user privacy and the security of information maintained in the app.

- [ ]  FE: Register new users
- [ ]  FE: Authenticate existing users
- [ ]  BE: API requests must be processed only if they originate from authenticated user sessions on the FE
