### ISSUE TITLE
Create a Search Results page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v26-bears-team-06#31]
# User Story

As a `registered user` or an `unregistered user`
I want to search for goods I'm interested in and filter the results
So I can find goods I want to purchase or those similar to ones I'm selling

# Tasks

- [ ] List of out all the categories available on the app
- [ ] Search for listings using information TBD

Create API routes in the BE
    - [ ]  Search for `categories` route
    - [ ]  Search for `listings` route (search criteria TBD)
