### ISSUE TITLE
New User Registration

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v26-bears-team-06#4]
# User Story

As a `new user`
I want to register myself with the app
So my information and privacy can be protected via authentication

# Tasks

- [ ]  Add a `registration` page to collect & validate user name, email address, city, state, zip code
- [ ]  Implement support for registration using GitHub, Google, Facebook, etc.
- [ ]  Create a `user profile` database table to contain this information
    Create API routes in the BE to manipulate this information 
    - [ ]  Create `user profile` route
    - [ ]  Update `user profile` route
    - [ ]  Delete `user profile` route
    - [ ]  Retrieve `user profile`  information for a specific email address

**Comment by jdmedlock** [comment]
# User Story

As a `new user`
I want to register myself with the app
So my information and privacy can be protected via authentication

# Tasks

- [ ]  Add a `registration` page to collect & validate user name, email address, city, state, zip code
- [ ]  Create a `user profile` database table to contain this information
    Create API routes in the BE to manipulate this information 
    - [ ]  Create `user profile` route
    - [ ]  Update `user profile` route
    - [ ]  Delete `user profile` route
    - [ ]  Retrieve `user profile`  information for a specific email address
